backend: 
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "our-services-card"
    preview: false
    label: "Our service"
    folder: "content/service-card"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'title', widget: "string"}
      - {label: 'content', name: 'content', widget: "markdown"}
      - {label: 'link', name: 'link', widget: "string"}
  - name: "services"
    preview: false
    label: "Service"
    folder: "content/service-page"
    create: false
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'title', widget: "string"}
      - {label: 'description', name: 'description', widget: "markdown"}
