backend: 
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "our-services-card"
    preview: false
    label: "Our service"
    folder: "content/service-card"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'title', widget: "string"}
      - {label: 'content', name: 'content', widget: "markdown"}
      - {label: 'link', name: 'link', widget: "string"}
  - name: "services"
    preview: false
    label: "Service"
    folder: "content/service-page"
    create: false
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'serviceTitle', widget: "string"}
      - {label: 'description', name: 'serviceDescription', widget: "markdown"}
  - name: "about-us"
    preview: false
    label: "About Us"
    folder: "content/about-us"
    create: false
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'aboutUsTitle', widget: "string"}
      - {label: 'Semi Title', name: 'aboutUsSemiTitle', widget: "string"}
      - {label: 'Description', name: 'aboutUsDescription', widget: "markdown"}
  - name: "about-us-card"
    preview: false
    label: "About Us Card"
    folder: "content/about-us-cards"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: 'title', name: 'aboutUsCardTitle', widget: "string"}
      - {label: 'Semi Title', name: 'aboutUsCardSemiTitle', widget: "string"}
      - {label: 'Description', name: 'aboutUsCardDescription', widget: "markdown"}
      - label: "Info Block"
        name: "modularWidget"
        widget: "list"
        fields:
          - {label: 'Title', name: 'title', widget: "string"}
          - {label: 'Semi Title', name: 'semiTitle', widget: "string"}

